apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: cron
rules:
  - apiGroups:
      - ""
    resources:
      - pods
    verbs:
      - get
      - list
  - apiGroups:
      - ""
    resources:
      - pods/exec
    verbs:
      - create

---
# You need to use that account for your dd-agent DaemonSet
kind: ServiceAccount
apiVersion: v1
metadata:
  name: cron
---
# Your admin user needs the same permissions to be able to grant them
# Easiest way is to bind your user to the cluster-admin role
# See https://cloud.google.com/container-engine/docs/role-based-access-control#setting_up_role-based_access_control
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cron
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cron
subjects:
  - kind: ServiceAccount
    name: cron